### POST request to example server
POST localhost:1013/api/doctors/doc
Content-Type: application/json

{
  "firstName": "Gena",
  "lastName": "Torchkov",
  "gender": "MALE",
  "email": "the100911oc@s1sssaswsmple.com",
  "phoneNumber": "+ 1 (888) 012 4977",
  "specialization": "Cardiologist",
  "rating": 0.0,
  "doctorStatus": "ACTIVE"
}

###