###
POST localhost:1010/patient
Content-Type: application/json

{
  "firstName": "Kakashi",
  "lastName": "Hatake",
  "gender": "MALE",
  "weight": 80.3,
  "height": 180.0,
  "email": "bkhponeemfm@test.com",
  "phoneNumber": "+133221952",
  "dateOfBirth": "1985-09-15",
  "address": "Konoha",
  "status": "ACTIVE",
  "registeredDate": "2023-04-01"
}
###