spring:
  application:
    name: meeting-service

feign:
  client:
    config:
      default:
       connectTimeout: 4000
       readTimeout: 4000
       loggerLevel: full
  circuitBreaker:
   enabled: true

server:
  port: 1012

logging:
  level:
    root: info
